# Generated by Django 5.2.17 on 2026-09-24 15:01

import dashboard.models
import dashboard.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNKNOWN', 'Not checked'), ('CHECKING', 'Checking…'), ('WAITING', 'Waiting for login'), ('AUTHENTICATED', 'Authenticated'), ('NOT_AUTH', 'Not logged in'), ('ERROR', 'Error'), ('MOCK', 'Mock mode')], default='UNKNOWN', max_length=16)),
                ('task', models.CharField(blank=True, help_text='Browser task currently running, if any.', max_length=20)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'browser session',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facebook_url', models.URLField(max_length=500, unique=True, validators=[dashboard.validators.validate_facebook_group_url], verbose_name='Facebook URL')),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('NEVER', 'Never run'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='NEVER', max_length=12)),
                ('last_error', models.TextField(blank=True)),
                ('total_posts', models.PositiveIntegerField(default=0)),
                ('completed_round', models.PositiveIntegerField(default=0)),
                ('url_check_status', models.CharField(blank=True, max_length=12)),
                ('url_check_message', models.CharField(blank=True, max_length=300)),
                ('url_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScraperSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('active', 'Active settings'), ('defaults', 'Saved defaults')], max_length=10, unique=True)),
                ('scraper_mode', models.CharField(choices=[('mock', 'Mock (simulated data)'), ('playwright', 'Playwright (real browser)')], default=dashboard.models.default_scraper_mode, max_length=12)),
                ('posts_per_group', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('groups_per_run', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('scroll_limit', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('scroll_delay', models.FloatField(default=2.0, help_text='Pause between scrolls. Keep this humane – at least 1 second.', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(60)], verbose_name='Scroll delay (seconds)')),
                ('page_timeout', models.PositiveIntegerField(default=45, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(180)], verbose_name='Page timeout (seconds)')),
                ('retry_count', models.PositiveIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(5)])),
                ('save_frequency', models.PositiveIntegerField(default=5, help_text='Posts are written to the database in batches of this size (and always at the end of a group).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Save every N posts')),
                ('save_after_every_group', models.BooleanField(default=True, help_text='Writes fetched_posts.json to the export directory after each group.', verbose_name='Export JSON snapshot after every group')),
                ('headless', models.BooleanField(default=False, help_text='Visible mode lets you log in manually if the session expires.', verbose_name='Headless browser')),
                ('browser_type', models.CharField(choices=[('chromium', 'Chromium')], default='chromium', max_length=20)),
                ('profile_dir', models.CharField(default=dashboard.models.default_profile_dir, max_length=500, verbose_name='Persistent profile directory')),
                ('auth_wait_seconds', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1800)], verbose_name='Wait for manual login (seconds)')),
                ('export_dir', models.CharField(default=dashboard.models.default_export_dir, max_length=500, verbose_name='Export directory')),
                ('log_level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], default='INFO', max_length=8)),
                ('log_retention_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)], verbose_name='Keep logs for (days)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'scraper setting',
            },
        ),
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], db_index=True, default='QUEUED', max_length=10)),
                ('current_phase', models.CharField(choices=[('IDLE', 'Idle'), ('SEEDING', 'Seeding'), ('INITIALIZING', 'Initializing'), ('AUTHENTICATING', 'Authenticating'), ('FETCHING', 'Fetching'), ('SCROLLING', 'Scrolling'), ('PARSING', 'Parsing'), ('SAVING', 'Saving'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='IDLE', max_length=16)),
                ('mode', models.CharField(choices=[('mock', 'Mock (simulated data)'), ('playwright', 'Playwright (real browser)')], default='mock', max_length=12)),
                ('trigger', models.CharField(default='web', help_text='web, cli or group', max_length=12)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('total_groups', models.PositiveIntegerField(default=0)),
                ('completed_groups', models.PositiveIntegerField(default=0)),
                ('failed_groups', models.PositiveIntegerField(default=0)),
                ('skipped_groups', models.PositiveIntegerField(default=0)),
                ('total_posts', models.PositiveIntegerField(default=0, help_text='New posts saved by this run.')),
                ('duplicate_posts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('stop_requested', models.BooleanField(default=False)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('worker_pid', models.PositiveIntegerField(blank=True, null=True)),
                ('current_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.group')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScraperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], db_index=True, default='INFO', max_length=8)),
                ('phase', models.CharField(blank=True, choices=[('IDLE', 'Idle'), ('SEEDING', 'Seeding'), ('INITIALIZING', 'Initializing'), ('AUTHENTICATING', 'Authenticating'), ('FETCHING', 'Fetching'), ('SCROLLING', 'Scrolling'), ('PARSING', 'Parsing'), ('SAVING', 'Saving'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], max_length=16)),
                ('message', models.TextField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='dashboard.group')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.scraperrun')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['run', 'id'], name='log_run_id_idx')],
            },
        ),
        migrations.CreateModel(
            name='RunGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('NEVER', 'Never run'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='QUEUED', max_length=12)),
                ('posts_collected', models.PositiveIntegerField(default=0)),
                ('duplicates', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_entries', to='dashboard.group')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_groups', to='dashboard.scraperrun')),
            ],
            options={
                'ordering': ['run', 'position'],
                'constraints': [models.UniqueConstraint(fields=('run', 'group'), name='unique_group_per_run')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_post_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('dedup_key', models.CharField(max_length=120, unique=True)),
                ('author_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('author_url', models.URLField(blank=True, max_length=1000)),
                ('post_text', models.TextField(blank=True)),
                ('post_url', models.URLField(blank=True, max_length=1000)),
                ('post_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('timestamp_text', models.CharField(blank=True, max_length=100)),
                ('collected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('media_url', models.URLField(blank=True, max_length=2000)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='dashboard.group')),
                ('run', models.ForeignKey(blank=True, help_text='The run that first collected this post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='dashboard.scraperrun')),
            ],
            options={
                'ordering': ['-collected_at', '-id'],
                'indexes': [models.Index(fields=['group', '-collected_at'], name='post_group_collected_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('facebook_post_id', ''), _negated=True), fields=('group', 'facebook_post_id'), name='unique_facebook_post_per_group')],
            },
        ),
    ]
